### ISSUE TITLE
Broken link on the "Creating a New Repository" page

### ISSUE THREAD

**Issue by chinmay185** [hmrc/hmrc.github.io#26]
A link (https://github.com/hmrc/jenkins-jobs) mentioned in the [Creating a new repository](https://github.com/hmrc/hmrc.github.io/blob/master/_posts/development-documentation/2015-01-28-creating-a-new-repository.md#next-steps) is broken. No such page exists and 404 is returned.

**Comment by agilestevesmith** [comment]
@chinmay185 There appear to be several broken links, thanks. Could you submit a PR? This repository is for all of us, after all
